wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1666987908.895865
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.9.7
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 15
